#!/bin/bash

for x in examples/*.fnjs; do
  b="$( basename "$x" .fnjs )"

  [[ "$b" == *NORUN* ]] && continue

  echo "running $x ..."
  ./bin/fnjs "$x" | ./_scripts/run-js > output/"$b".good.out
done

# --
