#!/bin/bash

vsn="$( cat _vsn )"

if [[ "$vsn" == *-dev ]]; then
  v="${vsn%-dev}-$( date +'%Y%m%d' )-$( git rev-parse --short HEAD )"
else
  v="$vsn"
fi

mkdir -p archive/fnjs-"$v"

cp -v -R tree/ archive/fnjs-"$v"/
tar czf fnjs-"$v".tgz -C archive fnjs-"$v"/

# --
