#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo 'Usage: set-vsn <vsn>' >&2
  exit 1
fi

# --

vsn="$1"

echo 'README ...'
sed -E -i '~' 's!(^Version *: *v)(.*)$!\1'"$vsn"'!' README

echo 'project.clj ...'
sed -E -i '~' 's!(^\(defproject +fnjs +")(.*)(")( *)$!\1'"$vsn"'\3!' \
  project.clj

echo 'bin/fnjs ...'
sed -E -i '~' 's!(^vsn='\'')(.*)('\'')( *)$!\1'"$vsn"'\3!' bin/fnjs

# --
