#!/bin/bash

e=test."$( date +'%Y%m%dT%H%M%S' )".js

for x in examples/*.fnjs; do
  b="$( basename "$x" .fnjs )"

  echo "processing $x ..." >&2
  ./bin/fnjs "$x" | ./_scripts/ugly | ./_scripts/fix-lambdas \
    > output/"$b.$e"

  for x in "${PIPESTATUS[@]}"; do
    if [ "$x" -ne 0 ]; then
      echo ERROR
      exit 1
    fi
  done

  if [ "$1" == -q ]; then
    if diff -q output/"$b".{good.js,"$e"}; then
      echo OK
    else
      echo DIFFERS
    fi
  else
    diff -Naur output/"$b".{good.js,"$e"}
  fi
done

# --
