#!/bin/bash

 e=test."$( date +'%Y%m%dT%H%M%S' )".out
ok=y

for x in examples/*.fnjs; do
  b="$( basename "$x" .fnjs )"

  [[ "$b" == *NORUN* ]] && continue

  echo "running $x ..." >&2
  ./bin/fnjs "$x" | ./_scripts/run-js > output/"$b.$e"

  for x in "${PIPESTATUS[@]}"; do
    if [ "$x" -ne 0 ]; then
      echo ERROR
      exit 1
    fi
  done

  if [ "$1" == -q ]; then
    if diff -q output/"$b".{good.out,"$e"}; then
      echo OK
    else
      ok=n
      echo DIFFERS
    fi
  else
    diff -Naur output/"$b".{good.out,"$e"}
  fi
done

[ "$ok" == y ] || exit 1

# --
