#!/bin/bash

e=test."$( date +'%Y%m%dT%H%M%S' )".out

for x in examples/*.fnjs; do
  b="$( basename "$x" .fnjs )"

  [[ "$b" == *web* ]] && continue

  echo "running $x ..." >&2
  ./bin/fnjs "$x" | node > output/"$b.$e"

  for x in "${PIPESTATUS[@]}"; do
    if [ "$x" -ne 0 ]; then
      echo ERROR
      exit 1
    fi
  done

  if [ "$1" == -q ]; then
    if diff -q output/"$b".{good.out,"$e"}; then
      echo OK
    else
      echo DIFFERS
    fi
  else
    diff -Naur output/"$b".{good.out,"$e"}
  fi
done

# --
