#!/bin/bash

e=test."$( date +'%Y%m%dT%H%M%S' )".out

for x in examples/*.fnjs; do
  b="$( basename "$x" .fnjs )"

  [[ "$b" == *web* ]] && continue

  echo "running $x ..." >&2
  ./bin/fnjs "$x" | node > output/"$b.$e"
  diff -Naur output/"$b".{good.out,"$e"}
done

# --
